version: '3.9'

services:
  bot:
    build: .
    env_file: .env
    ports:
      - $WEBAPP_PORT:$WEBAPP_PORT
    volumes:
      - .:/bot
    networks:
      - network1

networks:
  network1:
    name: $DOCKER_NETWORK_NAME
    external: $DOCKER_NETWORK_EXTERNAL
